const fs=require('fs');
const A='assets/';
function b64(f){return 'data:image/png;base64,'+fs.readFileSync(A+f).toString('base64');}
const arts={dex:b64('f2-dex-t.png'),pools:b64('f2-pools-t.png'),bridge:b64('f2-bridge-t.png'),rewards:b64('f2-rewards-t.png'),wallet:b64('f2-wallet-t.png')};
const P=[['dex','DEX','Orderbook and swap on the Hedera decentralized exchange.','Open DEX'],['pools','AMM Pools','Provide liquidity and earn trading fees from Hedera pools.','Open AMM'],['bridge','Cross-Chain Bridge','Move assets between Hedera and other networks.','Open Bridge'],['rewards','LUMOS Rewards','Track LP rewards and claim incentives in one place.','Open Rewards'],['wallet','My Wallet','Manage assets, trustlines, transfers, and orders.','Open Wallet']];
const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>';
function cards(){return P.map(function(p){return '<a class="pc" href="#"><img class="art" src="'+arts[p[0]]+'" alt=""><div class="pc-ttl">'+p[1]+'</div><div class="pc-desc">'+p[2]+'</div><div class="pc-go">'+p[3]+' '+arrow+'</div></a>';}).join('');}
const css=`[data-theme="dark"]{--bg:#0a0a0b;--surface:#131317;--border:#26262c;--text:#f6f5f3;--text-muted:#a5a4ac;--accent:#ea6a2c;--accent-pale:rgba(234,106,44,.12)}[data-theme="light"]{--bg:#f7f8fa;--surface:#fff;--border:#ececef;--text:#0e0e10;--text-muted:#5c5c66;--accent:#ea6a2c;--accent-pale:rgba(234,106,44,.10)}*{box-sizing:border-box}body{margin:0;font-family:'Hanken Grotesk',system-ui,sans-serif}.pane{padding:34px 40px;background:var(--bg)}.pane h2{margin:0 0 4px;font-size:26px;font-weight:800;letter-spacing:-.02em;color:var(--text)}.tag{font:600 11px monospace;color:var(--text-muted);letter-spacing:.1em;margin-bottom:18px;display:block}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;max-width:1120px}.pc{position:relative;overflow:hidden;border-radius:18px;padding:22px;text-decoration:none;display:flex;flex-direction:column;min-height:200px;background:var(--surface);border:1px solid var(--border);box-shadow:0 8px 24px -18px rgba(0,0,0,.5);transition:transform .18s,border-color .18s}.pc:hover{transform:translateY(-3px);border-color:var(--accent)}.pc::after{content:"";position:absolute;right:-24px;bottom:-30px;width:170px;height:170px;border-radius:50%;background:radial-gradient(circle,var(--accent-pale),transparent 68%);z-index:0}.pc .art{position:absolute;right:2px;top:50%;transform:translateY(-50%);width:132px;height:132px;object-fit:contain;z-index:1;opacity:.9;filter:drop-shadow(0 6px 16px rgba(234,106,44,.16))}.pc-ttl{position:relative;z-index:2;margin:0;font-size:19px;font-weight:800;letter-spacing:-.02em;color:var(--text)}.pc-desc{position:relative;z-index:2;margin:8px 0 0;font-size:14px;line-height:1.5;color:var(--text-muted);max-width:60%}.pc-go{position:relative;z-index:2;margin-top:auto;padding-top:16px;font-size:14px;font-weight:700;color:var(--accent);display:inline-flex;align-items:center;gap:6px}.pc-go svg{width:15px;height:15px}`;
const html='<!doctype html><html><head><meta charset="utf-8"><link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>'+css+'</style></head><body><div class="pane" data-theme="dark"><h2>Explore products</h2><span class="tag">FLAT ART · DARK</span><div class="grid">'+cards()+'</div></div><div class="pane" data-theme="light"><h2>Explore products</h2><span class="tag">FLAT ART · LIGHT</span><div class="grid">'+cards()+'</div></div></body></html>';
fs.writeFileSync('dist/_products-flat-inline.html',html);
console.log('wrote dist/_products-flat-inline.html',(html.length/1024|0)+'KB');
