// Generates _lib/verifiedseed.js from lib.js VERIFIED.
//
// GENERATED, NOT COPIED. lib.js is CommonJS and read by the transforms; functions/ are ESM modules run
// by the Worker, so the list cannot simply be imported across. Hand-copying it would create exactly the
// failure lib.js warns about at the top of VERIFIED -- a list that drifts between places, so an asset
// is trustworthy on one screen and not on the next. Re-run this whenever VERIFIED changes.
//
// Usage: node _tools/_genverifiedseed.js
const fs = require('fs');
const path = require('path');
const { VERIFIED } = require(__dirname + '/lib.js');

const OUT = path.join(__dirname, '..', '_lib', 'verifiedseed.js');

const entries = Object.keys(VERIFIED)
  .filter((k) => k.indexOf('|') > 0 && k.split('|')[1])   // XLM has no issuer and needs no listing
  .sort();

const body = entries.map((k) => '  ' + JSON.stringify(k) + ': ' + JSON.stringify(VERIFIED[k]) + ',').join('\n');

const src = `// GENERATED by _tools/_genverifiedseed.js from _tools/lib.js VERIFIED -- do not edit by hand.
//
// The issuer/domain pairs that were verified BEFORE the handshake ran server-side, each one checked at
// the time by reading the issuer's on-chain home_domain, fetching that domain's stellar.toml and
// confirming its [[CURRENCIES]] named the same code and issuer back.
//
// They are kept because a live handshake can now fail for an asset that is genuinely fine: USDC and
// EURC set home_domain = circle.com, and circle.com serves no stellar.toml any more (the old one is at
// centre.io, which is not the home_domain). Dropping their ticks would be wrong, and would look to a
// user exactly like the assets being fraudulent.
//
// New assets are NOT added here. They earn their tick from the live handshake, or they do not get one.
export const GRANDFATHERED = {
${body}
};

export const SEED = Object.keys(GRANDFATHERED);
`;

fs.writeFileSync(OUT, src, 'utf8');
console.log('verifiedseed.js: ' + entries.length + ' pairs -> _lib/verifiedseed.js');
