// GENERATED by _tools/extract_site.js — edit the ROUTES table there, not this file.
const MOBILE = /Android|iPhone|iPod|IEMobile|BlackBerry|Opera Mini|Mobile Safari|Windows Phone/i;
// [urlPattern, desktopFile, mobileFile|null] — "/" names both explicitly because its desktop file is
// index (fetching /lumoscore-landing would hit the 301 back to "/" and loop).
const ROUTES = [
  [
    "/",
    "index",
    "lumoscore-landing-mobile"
  ],
  [
    "/trade/stellar/:asset",
    "lumoscore-dex-asset",
    null
  ],
  [
    "/trade/stellar",
    "lumoscore-dex",
    null
  ],
  [
    "/account/stellar/:address",
    "lumoscore-account",
    null
  ],
  [
    "/pools/stellar/id/:pool",
    "lumoscore-amm-pool",
    null
  ],
  [
    "/pools/stellar/:a/:b",
    "lumoscore-amm-pool",
    null
  ],
  [
    "/pools/stellar",
    "lumoscore-amm",
    null
  ],
  [
    "/launchpad/review",
    "lumoscore-launch-review",
    null
  ],
  [
    "/launchpad/confirm",
    "lumoscore-launch-confirm",
    null
  ],
  [
    "/launchpad",
    "lumoscore-launch-token",
    null
  ],
  [
    "/dashboard",
    "lumoscore-home",
    null
  ],
  [
    "/bridge",
    "lumoscore-bridge",
    null
  ],
  [
    "/wallet",
    "lumoscore-wallet",
    null
  ],
  [
    "/rewards",
    "lumoscore-rewards-dark",
    null
  ],
  [
    "/lumos/stellar",
    "lumoscore-lumos-token",
    null
  ],
  [
    "/lumos",
    "lumoscore-lumos-token",
    null
  ],
  [
    "/signin",
    "lumoscore-signin",
    null
  ],
  [
    "/mcp",
    "lumoscore-mcp",
    null
  ],
  [
    "/blog",
    "lumoscore-blog",
    null
  ]
];
const HAS_MOBILE = new Set(["lumoscore-home-mobile","lumoscore-landing-mobile","lumoscore-launch-confirm-mobile","lumoscore-launch-review-mobile","lumoscore-launch-token-mobile","lumoscore-wallet-mobile","lumoscore-amm-mobile","lumoscore-amm-pool-mobile","lumoscore-lumos-token-mobile","lumoscore-dex-mobile","lumoscore-dex-asset-mobile","lumoscore-bridge-mobile","lumoscore-signin-mobile","lumoscore-rewards-mobile","lumoscore-mcp-mobile","lumoscore-account-mobile","lumoscore-blog-mobile"]);

function match(pathname){
  const segs = pathname.replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
  for (const r of ROUTES){
    const p = r[0].replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
    if (p.length !== segs.length) continue;
    let ok = true;
    for (let i = 0; i < p.length; i++){
      if (p[i].startsWith(':')) continue;
      if (p[i] !== segs[i]) { ok = false; break; }
    }
    // strip a theme suffix before deriving the mobile name: /rewards is served by
    // lumoscore-rewards-dark, whose mobile build is lumoscore-rewards-mobile — NOT
    // lumoscore-rewards-dark-mobile, which does not exist.
    if (ok) return { desktop: r[1], mobile: r[2] || (r[1].replace(/-(dark|light)$/, '') + '-mobile') };
  }
  return null;
}

// ---- per-page SEO, injected at the edge ---------------------------------------------------------
// /trade/stellar/<ASSET> is ONE file serving hundreds of assets, so without this every asset page
// ships an identical title and description — duplicate content on exactly the pages that could rank.
// Crawlers that do not run JavaScript (GPTBot, ClaudeBot, PerplexityBot) see only what arrives in the
// HTML, so the runtime title the page sets for itself is invisible to them. Injecting here fixes both.
//
// The host comes from the request, so no domain is hardcoded anywhere.
const SEO_CACHE_TTL = 300;

// The site's ONE canonical origin. Every canonical/og:url points here regardless of which host served
// the request, so the *.pages.dev preview url cannot compete with the real domain in search results.
const PRIMARY_ORIGIN = 'https://lumoscore.com';

function esc(s){
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function fmtUsd(n){
  if (n == null || !isFinite(n)) return null;
  if (n >= 1000) return '$' + Math.round(n).toLocaleString('en-US');
  if (n < 0.0001) return '$' + Number(n).toPrecision(3);
  return '$' + Number(n).toFixed(n < 1 ? 4 : 2);
}

async function assetFacts(assetId){
  try {
    const r = await fetch(
      'https://api.stellar.expert/explorer/public/asset?search=' + encodeURIComponent(assetId) + '&limit=5',
      { cf: { cacheTtl: SEO_CACHE_TTL, cacheEverything: true } });
    if (!r.ok) return null;
    const d = await r.json();
    const recs = (d && d._embedded && d._embedded.records) || [];
    const m = recs.filter(x => String(x.asset || '').indexOf(assetId) === 0)[0];
    if (!m) return null;
    const toml = m.tomlInfo || m.toml_info || {};
    return {
      code: assetId.split('-')[0],
      price: +m.price || null,
      trustlines: (m.trustlines && m.trustlines[0]) || 0,
      domain: m.domain || '',
      image: toml.image || '',
      name: toml.name || '',
    };
  } catch (e) { return null; }
}

function assetSeo(f, assetId){
  const code = f ? f.code : assetId.split('-')[0];
  const bits = [];
  const px = f && fmtUsd(f.price);
  if (px) bits.push('Price ' + px);
  if (f && f.trustlines) bits.push(f.trustlines.toLocaleString('en-US') + ' trustlines');
  if (f && f.domain) bits.push('issued by ' + f.domain);
  const facts = bits.length ? bits.join(' · ') + '. ' : '';
  return {
    title: code + ' price, pools and holders on Stellar | LumosCore',
    desc: (facts + 'Live ' + code + ' price, liquidity pools, top holders and recent trades on the '
      + 'Stellar network. Buy or sell ' + code + ' non-custodially from your own wallet.').slice(0, 300),
    image: (f && f.image) || '',
  };
}

function poolSeo(a, b){
  const A = a === 'native' ? 'XLM' : a.split('-')[0];
  const B = b === 'native' ? 'XLM' : b.split('-')[0];
  return {
    title: A + ' / ' + B + ' liquidity pool on Stellar | LumosCore',
    desc: 'Reserves, total value locked, 24h volume and fees for the ' + A + ' / ' + B
      + ' liquidity pool on Stellar. Add or withdraw liquidity from your own wallet.',
    image: '',
  };
}

function seoFor(pathname){
  const segs = pathname.split('/').filter(Boolean);
  if ((segs[0] === 'trade' || segs[0] === 'asset') && segs[2]) return { kind: 'asset', id: segs[2] };
  if (segs[0] === 'pools' && segs[2] && segs[3]) return { kind: 'pool', a: segs[2], b: segs[3] };
  return null;
}

class HeadInjector {
  constructor(html){ this.html = html; this.done = false; }
  element(el){ if (this.done) return; this.done = true; el.append(this.html, { html: true }); }
}
class TitleSetter {
  constructor(t){ this.t = t; }
  element(el){ el.setInnerContent(this.t); }
}

// Legacy build filename -> clean url, as a REAL redirect.
//
// The build rewrites static hrefs and the runtime maps lxNavigate/clicks, but the app also navigates
// by assigning location.href="lumoscore-x.html?..." directly in a dozen places (_dexdata, _trending,
// _walletdata, _feemodal, …) and through a second helper, __lxNav. Chasing every call site is
// whack-a-mole; redirecting at the edge catches all of them, including any added later.
//
// Done HERE rather than in _redirects on purpose: a 301 there can collide with the 200-rewrite for
// the same page and loop. Here the order is explicit and the rewrite path uses env.ASSETS/next(),
// which never re-enters this check.
function legacyClean(pathname, params){
  // Take the LAST path segment, not the whole path. The app navigates with RELATIVE urls
  // (location.href="lumoscore-dex-asset.html?asset=…"), which used to resolve at the site root but
  // now resolve against a nested clean url — /trade/stellar + "lumoscore-dex-asset.html" becomes
  // /trade/lumoscore-dex-asset.html and 404s. Matching the last segment redirects it from any depth.
  //
  // plain string ops, not regex: this file is emitted from a template literal, where a lone
  // backslash does not survive and silently corrupts the pattern.
  const segs = pathname.split('/');
  let base = segs[segs.length - 1] || '';
  if (base.slice(-5) === '.html') base = base.slice(0, -5);
  if (!base.startsWith('lumoscore-')) return null;
  base = base.replace(/-(dark|light|mobile)$/, '');

  // the two dynamic routes carry their identifier in the query — promote it into the path
  const asset = params && params.get('asset');
  if (base === 'lumoscore-dex-asset')      return asset ? '/trade/stellar/' + asset : '/trade/stellar';
  if (base === 'lumoscore-asset-overview') return asset ? '/trade/stellar/' + asset : '/trade/stellar';
  // a pool is addressed by its two assets, which ?pool=<id> does not carry — leave it alone
  const pool = params && params.get('pool');
  if (base === 'lumoscore-amm-pool') return pool ? '/pools/stellar/id/' + pool : '/pools/stellar';

  // "/" is registered in ROUTES against "index" (the landing page is copied to index.html so the
  // front door is not a redirect), so the ROUTES loop below never matches "lumoscore-landing" and
  // returned null. That mattered because the wallet gate used to redirect with the bare filename:
  // from /asset/stellar/<ASSET> the browser asked for /asset/stellar/lumoscore-landing.html, no 301
  // fired, and "/asset/stellar/:asset" then matched with the asset literally being
  // "lumoscore-landing.html" — rendering an asset page for an asset that does not exist, i.e. blank.
  if (base === 'lumoscore-landing') return '/';

  for (const r of ROUTES){
    if (r[0].indexOf('/:') >= 0) continue;
    if (r[1].replace(/-(dark|light|mobile)$/, '') === base) return r[0];
  }
  return null;
}

export async function onRequest(context){
  const { request, next } = context;
  const url = new URL(request.url);

  // 0) ONE ORIGIN. www.lumoscore.com was serving the whole app on a 200 with no redirect, so the site
  // answered on two hostnames — and a browser keeps localStorage PER ORIGIN. The wallet session lives
  // there (lumos.wallet / lumos.address), so connecting on one host and later arriving on the other
  // looked exactly like being logged out, with no way for the user to tell why. It also split every
  // SEO signal in spite of the canonical tag pointing at the apex. 301 so the browser stops asking.
  if (url.hostname.startsWith('www.')){
    const to = new URL(url.toString());
    to.hostname = url.hostname.slice(4);
    return Response.redirect(to.toString(), 301);
  }

  // 1) someone navigated to a raw build filename -> send them to the canonical clean url
  const legacy = legacyClean(url.pathname, url.searchParams);
  if (legacy){
    const to = new URL(legacy, url.origin);
    // ?asset= / ?pool= became a path segment, so carrying THEM would duplicate the identifier — but
    // dropping the whole query took every OTHER param with it. That silently broke the Wallet's
    // "Remove" button on an LP position, which links to ...?pool=<id>&act=withdraw so the pool page
    // opens on the Withdraw tab: the redirect promoted the pool into the path and threw act= away, so
    // the user always landed on Deposit. Drop only the key that was promoted.
    const promoted = legacy.indexOf('/trade/stellar/') === 0
      || legacy.indexOf('/pools/stellar/id/') === 0;
    if (promoted){
      const keep = new URLSearchParams(url.search);
      keep.delete('asset'); keep.delete('pool');
      const qs = keep.toString();
      to.search = qs ? ('?' + qs) : '';
    } else to.search = url.search;
    to.hash = url.hash;
    return Response.redirect(to.toString(), 301);
  }

  // 1b) /asset/stellar/<ASSET> -> /trade/stellar/<ASSET>, permanently.
  // The asset-overview page was removed; Trade-asset shows the same facts and can act on them.
  // These urls were published in the sitemap and may already be indexed, so this is a 301 rather
  // than a 404: search engines transfer the ranking to the Trade page instead of dropping it.
  // Bare /asset/stellar (no asset) goes to the Trade list.
  if (url.pathname === '/asset/stellar' || url.pathname.indexOf('/asset/stellar/') === 0){
    const rest = url.pathname.slice('/asset/stellar'.length);
    const to = new URL('/trade/stellar' + rest, url.origin);
    to.search = url.search;
    to.hash = url.hash;
    return Response.redirect(to.toString(), 301);
  }

  const hit = match(url.pathname);

  // not a page route -> let Pages serve it as usual
  if (!hit) return next();

  const isMobile = MOBILE.test(request.headers.get('user-agent') || '');
  const wantMobile = isMobile && HAS_MOBILE.has(hit.mobile);

  // Desktop needs no rewrite — Pages already serves the right file for this url. Rewriting anyway
  // broke "/", whose desktop file is index: fetching /index just 308s back to /.
  // Vary is still set on BOTH branches, or a cache would hand a desktop page to a phone.
  const res = wantMobile
    ? await context.env.ASSETS.fetch(
        new Request(new URL('/' + hit.mobile, request.url).toString(), request))
    : await next();

  let out = new Response(res.body, res);
  out.headers.set('Vary', 'User-Agent');

  const ct = out.headers.get('content-type') || '';
  if (ct.indexOf('text/html') < 0) return out;

  // canonical is the clean url WITHOUT query or hash, on whatever host served this request
  const canonical = PRIMARY_ORIGIN + (url.pathname === '/' ? '/' : url.pathname.replace(/\/+$/, ''));
  const want = seoFor(url.pathname);

  let seo = null;
  if (want && want.kind === 'asset') seo = assetSeo(await assetFacts(want.id), want.id);
  else if (want && want.kind === 'pool') seo = poolSeo(want.a, want.b);

  const head = [
    '<link rel="canonical" href="' + esc(canonical) + '">',
    '<meta property="og:url" content="' + esc(canonical) + '">',
    '<meta property="og:site_name" content="LumosCore">',
    '<meta property="og:type" content="website">',
    '<meta name="twitter:card" content="summary_large_image">',
  ];
  if (seo){
    head.push('<meta property="og:title" content="' + esc(seo.title) + '">');
    head.push('<meta property="og:description" content="' + esc(seo.desc) + '">');
    head.push('<meta name="twitter:title" content="' + esc(seo.title) + '">');
    head.push('<meta name="twitter:description" content="' + esc(seo.desc) + '">');
    if (seo.image) head.push('<meta property="og:image" content="' + esc(seo.image) + '">');
    // a description already exists from the build; replace rather than duplicate
    head.push('<meta name="lx-seo-desc" content="' + esc(seo.desc) + '">');
  }

  let rw = new HTMLRewriter().on('head', new HeadInjector(head.join('')));
  if (seo){
    rw = rw.on('title', new TitleSetter(seo.title))
           .on('meta[name="description"]', {
             element(el){ el.setAttribute('content', seo.desc); },
           });
  }
  out = rw.transform(out);
  out.headers.set('Vary', 'User-Agent');
  return out;
}
