// GENERATED by _tools/extract_site.js — edit the ROUTES table there, not this file.
const MOBILE = /Android|iPhone|iPod|IEMobile|BlackBerry|Opera Mini|Mobile Safari|Windows Phone/i;
// [urlPattern, desktopFile, mobileFile|null] — "/" names both explicitly because its desktop file is
// index (fetching /lumoscore-landing would hit the 301 back to "/" and loop).
const ROUTES = [
  [
    "/",
    "index",
    "lumoscore-landing-mobile"
  ],
  [
    "/trade/stellar/:asset",
    "lumoscore-dex-asset",
    null
  ],
  [
    "/trade/stellar",
    "lumoscore-dex",
    null
  ],
  [
    "/account/stellar/:address",
    "lumoscore-account",
    null
  ],
  [
    "/pools/stellar/id/:pool",
    "lumoscore-amm-pool",
    null
  ],
  [
    "/pools/stellar/:a/:b",
    "lumoscore-amm-pool",
    null
  ],
  [
    "/pools/stellar",
    "lumoscore-amm",
    null
  ],
  [
    "/launchpad/review",
    "lumoscore-launch-review",
    null
  ],
  [
    "/launchpad/confirm",
    "lumoscore-launch-confirm",
    null
  ],
  [
    "/launchpad",
    "lumoscore-launch-token",
    null
  ],
  [
    "/dashboard",
    "lumoscore-home",
    null
  ],
  [
    "/bridge",
    "lumoscore-bridge",
    null
  ],
  [
    "/wallet",
    "lumoscore-wallet",
    null
  ],
  [
    "/rewards",
    "lumoscore-rewards-dark",
    null
  ],
  [
    "/lumos/stellar",
    "lumoscore-lumos-token",
    null
  ],
  [
    "/lumos",
    "lumoscore-lumos-token",
    null
  ],
  [
    "/signin",
    "lumoscore-signin",
    null
  ],
  [
    "/mcp",
    "lumoscore-mcp",
    null
  ],
  [
    "/blog/:slug",
    "lumoscore-blog-post",
    null
  ],
  [
    "/blog",
    "lumoscore-blog",
    null
  ],
  [
    "/privacy",
    "lumoscore-privacy",
    null
  ],
  [
    "/terms",
    "lumoscore-terms",
    null
  ],
  [
    "/support",
    "lumoscore-support",
    null
  ],
  [
    "/whitepaper",
    "lumoscore-whitepaper",
    null
  ],
  [
    "/about",
    "lumoscore-about",
    null
  ],
  [
    "/list-your-token",
    "lumoscore-list-token",
    null
  ],
  [
    "/docs/introduction",
    "lumoscore-docs-introduction",
    null
  ],
  [
    "/docs/connect-a-wallet",
    "lumoscore-docs-connect-a-wallet",
    null
  ],
  [
    "/docs/fees",
    "lumoscore-docs-fees",
    null
  ],
  [
    "/docs/swaps",
    "lumoscore-docs-swaps",
    null
  ],
  [
    "/docs/limit-orders",
    "lumoscore-docs-limit-orders",
    null
  ],
  [
    "/docs/liquidity-pools",
    "lumoscore-docs-liquidity-pools",
    null
  ],
  [
    "/docs/cross-chain",
    "lumoscore-docs-cross-chain",
    null
  ],
  [
    "/docs/wallet",
    "lumoscore-docs-wallet",
    null
  ],
  [
    "/docs/trustlines",
    "lumoscore-docs-trustlines",
    null
  ],
  [
    "/docs/rewards",
    "lumoscore-docs-rewards",
    null
  ],
  [
    "/docs/launch-a-token",
    "lumoscore-docs-launch-a-token",
    null
  ],
  [
    "/docs/asset-metadata",
    "lumoscore-docs-asset-metadata",
    null
  ],
  [
    "/docs/verification",
    "lumoscore-docs-verification",
    null
  ],
  [
    "/docs/curated-listing",
    "lumoscore-docs-curated-listing",
    null
  ],
  [
    "/docs/security",
    "lumoscore-docs-security",
    null
  ],
  [
    "/docs/troubleshooting",
    "lumoscore-docs-troubleshooting",
    null
  ],
  [
    "/docs/faq",
    "lumoscore-docs-faq",
    null
  ],
  [
    "/docs",
    "lumoscore-docs-introduction",
    null
  ],
  [
    "/faq",
    "lumoscore-docs-faq",
    null
  ]
];
const HAS_MOBILE = new Set(["lumoscore-home-mobile","lumoscore-landing-mobile","lumoscore-launch-confirm-mobile","lumoscore-launch-review-mobile","lumoscore-launch-token-mobile","lumoscore-wallet-mobile","lumoscore-amm-mobile","lumoscore-amm-pool-mobile","lumoscore-lumos-token-mobile","lumoscore-dex-mobile","lumoscore-dex-asset-mobile","lumoscore-bridge-mobile","lumoscore-signin-mobile","lumoscore-rewards-mobile","lumoscore-mcp-mobile","lumoscore-account-mobile","lumoscore-blog-mobile","lumoscore-blog-post-mobile","lumoscore-privacy-mobile","lumoscore-terms-mobile","lumoscore-support-mobile","lumoscore-whitepaper-mobile","lumoscore-docs-introduction-mobile","lumoscore-docs-connect-a-wallet-mobile","lumoscore-docs-fees-mobile","lumoscore-docs-swaps-mobile","lumoscore-docs-limit-orders-mobile","lumoscore-docs-liquidity-pools-mobile","lumoscore-docs-cross-chain-mobile","lumoscore-docs-wallet-mobile","lumoscore-docs-trustlines-mobile","lumoscore-docs-rewards-mobile","lumoscore-docs-launch-a-token-mobile","lumoscore-docs-asset-metadata-mobile","lumoscore-docs-verification-mobile","lumoscore-docs-curated-listing-mobile","lumoscore-docs-security-mobile","lumoscore-docs-troubleshooting-mobile","lumoscore-docs-faq-mobile","lumoscore-about-mobile","lumoscore-list-token-mobile"]);

function match(pathname){
  const segs = pathname.replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
  for (const r of ROUTES){
    const p = r[0].replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
    if (p.length !== segs.length) continue;
    let ok = true;
    for (let i = 0; i < p.length; i++){
      if (p[i].startsWith(':')) continue;
      if (p[i] !== segs[i]) { ok = false; break; }
    }
    // strip a theme suffix before deriving the mobile name: /rewards is served by
    // lumoscore-rewards-dark, whose mobile build is lumoscore-rewards-mobile — NOT
    // lumoscore-rewards-dark-mobile, which does not exist.
    if (ok) return { desktop: r[1], mobile: r[2] || (r[1].replace(/-(dark|light)$/, '') + '-mobile') };
  }
  return null;
}

// ---- per-page SEO, injected at the edge ---------------------------------------------------------
// /trade/stellar/<ASSET> is ONE file serving hundreds of assets, so without this every asset page
// ships an identical title and description — duplicate content on exactly the pages that could rank.
// Crawlers that do not run JavaScript (GPTBot, ClaudeBot, PerplexityBot) see only what arrives in the
// HTML, so the runtime title the page sets for itself is invisible to them. Injecting here fixes both.
//
// The host comes from the request, so no domain is hardcoded anywhere.
const SEO_CACHE_TTL = 300;

// The site's ONE canonical origin. Every canonical/og:url points here regardless of which host served
// the request, so the *.pages.dev preview url cannot compete with the real domain in search results.
const PRIMARY_ORIGIN = 'https://lumoscore.com';

function esc(s){
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function fmtUsd(n){
  if (n == null || !isFinite(n)) return null;
  if (n >= 1000) return '$' + Math.round(n).toLocaleString('en-US');
  // toPrecision(3) goes exponential below about 1e-6, so a genuinely cheap token shipped its price
  // into the search result as "$7.72e-7" -- which reads as a bug to a person and is not a number a
  // language model restates cleanly. Plenty of Stellar assets sit down there.
  //
  // Zero and negative are guarded before the log, which would otherwise be -Infinity and ask toFixed
  // for 100 decimals -- that trimmed back to a bare "$0." once the zeros were stripped.
  if (!(n > 0)) return null;
  if (n < 0.0001) {
    const places = Math.min(100, Math.max(4, 2 - Math.floor(Math.log10(n))));
    return '$' + Number(n).toFixed(places).replace(/0+$/, '').replace(/\.$/, '');
  }
  return '$' + Number(n).toFixed(n < 1 ? 4 : 2);
}

async function assetFacts(assetId){
  try {
    const r = await fetch(
      'https://api.stellar.expert/explorer/public/asset?search=' + encodeURIComponent(assetId) + '&limit=5',
      { cf: { cacheTtl: SEO_CACHE_TTL, cacheEverything: true } });
    if (!r.ok) return null;
    const d = await r.json();
    const recs = (d && d._embedded && d._embedded.records) || [];
    const m = recs.filter(x => String(x.asset || '').indexOf(assetId) === 0)[0];
    if (!m) return null;
    const toml = m.tomlInfo || m.toml_info || {};
    return {
      code: assetId.split('-')[0],
      price: +m.price || null,
      trustlines: (m.trustlines && m.trustlines[0]) || 0,
      domain: m.domain || '',
      image: toml.image || '',
      name: toml.name || '',
      desc: String(toml.desc || toml.description || '').slice(0, 400),
    };
  } catch (e) { return null; }
}

function assetSeo(f, assetId){
  const code = f ? f.code : assetId.split('-')[0];
  const bits = [];
  const px = f && fmtUsd(f.price);
  if (px) bits.push('Price ' + px);
  if (f && f.trustlines) bits.push(f.trustlines.toLocaleString('en-US') + ' trustlines');
  if (f && f.domain) bits.push('issued by ' + f.domain);
  const facts = bits.length ? bits.join(' · ') + '. ' : '';
  return {
    title: code + ' price, pools and holders on Stellar | LumosCore',
    // Search results truncate around 160 characters and the FACTS are the half worth showing, so
    // the boilerplate tail is trimmed rather than the price and trustline count.
    desc: (facts + code + ' price, pools, holders and trades on Stellar. Trade non-custodially.')
      .slice(0, 158),
    image: (f && f.image) || '',
  };
}

function poolSeo(a, b, img){
  const A = a === 'native' ? 'XLM' : a.split('-')[0];
  const B = b === 'native' ? 'XLM' : b.split('-')[0];
  return {
    title: A + ' / ' + B + ' liquidity pool on Stellar | LumosCore',
    desc: 'Reserves, total value locked, 24h volume and fees for the ' + A + ' / ' + B
      + ' liquidity pool on Stellar. Add or withdraw liquidity from your own wallet.',
    image: img || '',
  };
}

// A purpose-built card is landscape; an asset's toml logo is a small square (SHX's is 128x128).
// Declaring a square as a large-image card is why scrapers dropped it and used the favicon instead.
function isCardImage(u){ return String(u || '').indexOf('/lxapi/ogcard') >= 0; }

// A 1200x630 card: the asset's logo padded onto the brand background. Built through Cloudflare's
// resizing, whose source must be on this zone -- hence /lxapi/logoimg re-serving foreign logos.
// One plain URL. The 1200x630 padding happens inside the endpoint, so nothing is nested here.
function cardFor(assetId){
  if (!assetId) return '';
  return PRIMARY_ORIGIN + '/lxapi/ogcard?asset=' + encodeURIComponent(assetId);
}

// The logo an admin uploaded for an asset, which the issuer's toml knows nothing about.
async function adminImage(env, assetId){
  try {
    const kv = env && env.CONTENT_KV;
    if (!kv || !assetId) return '';
    const ov = await kv.get('asset:' + assetId, 'json');
    return (ov && ov.image) || '';
  } catch (e) { return ''; }
}
// og:image is fetched by a scraper with no page context, so a relative path is useless to it.
function absUrl(u){
  const v = String(u || '');
  if (!v) return '';
  if (v.indexOf('//') === 0) return 'https:' + v;
  if (v.indexOf('/') === 0) return PRIMARY_ORIGIN + v;
  return v;
}

// A published post, read from the same KV the blog itself reads. Unpublished or missing returns null
// so the page keeps its template SEO rather than advertising something that is not there.
async function blogPost(env, slug){
  try {
    const kv = env && env.CONTENT_KV;
    if (!kv || !slug) return null;
    const p = await kv.get('blog:post:' + slug, 'json');
    if (!p || p.published === false) return null;
    return p;
  } catch (e) { return null; }
}
// Whitespace, built without a backslash: this whole function lives inside a template literal, where a
// backslash is eaten on the way out. Writing /BACKSLASH-s+/g here produced /s+/g, which matched the
// letter s and quietly deleted every one of them from the description.
const WS_RE = new RegExp('[' + String.fromCharCode(32, 9, 10, 13) + ']+', 'g');

// The excerpt if the author wrote one, otherwise the opening of the body with its markup removed.
function blogDesc(p){
  const ex = String((p && p.excerpt) || '').trim();
  if (ex) return ex.slice(0, 300);
  const body = String((p && p.body) || '')
    .replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/gi, ' ').replace(WS_RE, ' ').trim();
  return body.slice(0, 155) + (body.length > 155 ? '…' : '');
}
function blogSeo(p, origin){
  // The stored title already ends in "| LumosCore" on existing posts, so it is not appended twice.
  const t = String((p && p.title) || '').trim();
  // endsWith rather than a pattern: no backslash to lose, and it says what it means.
  const title = t.toLowerCase().replace(WS_RE, ' ').trim().endsWith('lumoscore')
    ? t : (t + ' | LumosCore');
  const cover = String((p && p.cover) || '');
  return {
    title,
    desc: blogDesc(p),
    image: cover ? (cover.indexOf('/') === 0 ? origin + cover : cover) : '',
    post: p,
  };
}

function seoFor(pathname){
  const segs = pathname.split('/').filter(Boolean);
  if ((segs[0] === 'trade' || segs[0] === 'asset') && segs[2]) return { kind: 'asset', id: segs[2] };
  if (segs[0] === 'pools' && segs[2] && segs[3]) return { kind: 'pool', a: segs[2], b: segs[3] };
  if (segs[0] === 'blog' && segs[1]) return { kind: 'blog', slug: segs[1] };
  return null;
}

// Replaces an element's text. Used on the asset identity block, whose shipped markup is the design's
// USDC sample: without this, every asset page tells a non-rendering crawler it is USD Coin.
// NOTE the property is v, not text: naming it "text" shadows the text() handler HTMLRewriter calls
// on this same object, which is exactly how this threw Error 1101 on every asset page.
//
// mode 'inner' replaces the element's contents outright — correct where the element holds only text.
// mode 'text' rewrites text nodes only, leaving child elements alone; a.website holds an SVG icon
// beside the domain and would lose it otherwise.
class TextSetter {
  constructor(v, mode){
    this.v = String(v == null ? '' : v);
    this.mode = mode === 'text' ? 'text' : 'inner';
    this.first = true;
  }
  element(el){
    this.first = true;
    if (this.mode === 'inner') el.setInnerContent(this.v);
  }
  text(chunk){
    if (this.mode === 'inner') return;
    const t = chunk.text;
    if (!t || !t.trim()) return;              // whitespace between the icon and the label
    chunk.replace(this.first ? this.v : '', { html: false });
    this.first = false;
  }
}

// Writes stored HTML into an element. Only the blog body uses this, and only with markup that came
// back through the sanitiser in lxapi/blog.js -- setInnerContent with html:true is parsed as real
// markup, so a <script> in there would RUN, where the client's innerHTML would not have executed it.
// That difference is the whole reason the allowlist moved server-side.
class HtmlSetter {
  constructor(html){ this.html = String(html == null ? '' : html); }
  element(el){ if (this.html) el.setInnerContent(this.html, { html: true }); }
}

class HeadInjector {
  constructor(html){ this.html = html; this.done = false; }
  element(el){ if (this.done) return; this.done = true; el.append(this.html, { html: true }); }
}
class TitleSetter {
  constructor(t){ this.t = t; }
  element(el){ el.setInnerContent(this.t); }
}

// Legacy build filename -> clean url, as a REAL redirect.
//
// The build rewrites static hrefs and the runtime maps lxNavigate/clicks, but the app also navigates
// by assigning location.href="lumoscore-x.html?..." directly in a dozen places (_dexdata, _trending,
// _walletdata, _feemodal, …) and through a second helper, __lxNav. Chasing every call site is
// whack-a-mole; redirecting at the edge catches all of them, including any added later.
//
// Done HERE rather than in _redirects on purpose: a 301 there can collide with the 200-rewrite for
// the same page and loop. Here the order is explicit and the rewrite path uses env.ASSETS/next(),
// which never re-enters this check.
function legacyClean(pathname, params){
  // Take the LAST path segment, not the whole path. The app navigates with RELATIVE urls
  // (location.href="lumoscore-dex-asset.html?asset=…"), which used to resolve at the site root but
  // now resolve against a nested clean url — /trade/stellar + "lumoscore-dex-asset.html" becomes
  // /trade/lumoscore-dex-asset.html and 404s. Matching the last segment redirects it from any depth.
  //
  // plain string ops, not regex: this file is emitted from a template literal, where a lone
  // backslash does not survive and silently corrupts the pattern.
  const segs = pathname.split('/');
  let base = segs[segs.length - 1] || '';
  if (base.slice(-5) === '.html') base = base.slice(0, -5);
  if (!base.startsWith('lumoscore-')) return null;
  base = base.replace(/-(dark|light|mobile)$/, '');

  // the two dynamic routes carry their identifier in the query — promote it into the path
  const asset = params && params.get('asset');
  if (base === 'lumoscore-dex-asset')      return asset ? '/trade/stellar/' + asset : '/trade/stellar';
  if (base === 'lumoscore-asset-overview') return asset ? '/trade/stellar/' + asset : '/trade/stellar';
  // a pool is addressed by its two assets, which ?pool=<id> does not carry — leave it alone
  const pool = params && params.get('pool');
  if (base === 'lumoscore-amm-pool') return pool ? '/pools/stellar/id/' + pool : '/pools/stellar';

  // "/" is registered in ROUTES against "index" (the landing page is copied to index.html so the
  // front door is not a redirect), so the ROUTES loop below never matches "lumoscore-landing" and
  // returned null. That mattered because the wallet gate used to redirect with the bare filename:
  // from /asset/stellar/<ASSET> the browser asked for /asset/stellar/lumoscore-landing.html, no 301
  // fired, and "/asset/stellar/:asset" then matched with the asset literally being
  // "lumoscore-landing.html" — rendering an asset page for an asset that does not exist, i.e. blank.
  if (base === 'lumoscore-landing') return '/';

  for (const r of ROUTES){
    if (r[0].indexOf('/:') >= 0) continue;
    if (r[1].replace(/-(dark|light|mobile)$/, '') === base) return r[0];
  }
  return null;
}

// Shapes, not existence. A Stellar public key is 56 characters of base32 starting with G; an asset id
// is CODE-ISSUER; a pool id is 64 hex. Built with String.fromCharCode where a character class would
// otherwise need a backslash, because this whole file is emitted from a template literal and a lone
// backslash does not survive the trip.
const G_RE = new RegExp('^G[A-Z2-7]{55}$');
const ASSET_RE = new RegExp('^[A-Za-z0-9]{1,12}-G[A-Z2-7]{55}$');
const POOLID_RE = new RegExp('^[0-9a-fA-F]{64}$');
function malformedId(pathname){
  const s = pathname.replace(/^\/+|\/+$/g, '').split('/').filter(Boolean);
  // A percent-encoded segment that will not decode is malformed by definition, so the original is
  // tested and fails the shape check rather than throwing.
  const dec = (x) => { try { return decodeURIComponent(x); } catch (e) { return x; } };
  if (s[0] === 'trade' && s[1] === 'stellar' && s.length === 3){
    return !ASSET_RE.test(dec(s[2]));
  }
  if (s[0] === 'account' && s[1] === 'stellar' && s.length === 3){
    return !G_RE.test(dec(s[2]));
  }
  if (s[0] === 'pools' && s[1] === 'stellar' && s[2] === 'id' && s.length === 4){
    return !POOLID_RE.test(dec(s[3]));
  }
  // The pair form. "native" is XLM and has no issuer, so it is the one value that is not an asset id.
  if (s[0] === 'pools' && s[1] === 'stellar' && s.length === 4){
    const okSide = (x) => x === 'native' || ASSET_RE.test(x);
    return !(okSide(dec(s[2])) && okSide(dec(s[3])));
  }
  return false;
}

export async function onRequest(context){
  const { request, next } = context;
  const url = new URL(request.url);

  // 0) ONE ORIGIN. www.lumoscore.com was serving the whole app on a 200 with no redirect, so the site
  // answered on two hostnames — and a browser keeps localStorage PER ORIGIN. The wallet session lives
  // there (lumos.wallet / lumos.address), so connecting on one host and later arriving on the other
  // looked exactly like being logged out, with no way for the user to tell why. It also split every
  // SEO signal in spite of the canonical tag pointing at the apex. 301 so the browser stops asking.
  if (url.hostname.startsWith('www.')){
    const to = new URL(url.toString());
    to.hostname = url.hostname.slice(4);
    return Response.redirect(to.toString(), 301);
  }

  // 0b) A TRAILING SLASH IS THE SAME PAGE, so it must redirect rather than 404.
  //
  // Every path answered 404 with a slash on the end: /blog/, /about/, /docs/, /faq/, /lumos/,
  // /bridge/. People append them by habit, directory forms normalise to them, and forum software adds
  // them -- so each was a dead link carrying nothing, and a backlink placed on the wrong form of the
  // url was simply wasted.
  //
  // 301, because the canonical form is the one without. Query and hash ride along. The root is left
  // alone: "/" IS the canonical path and trimming it would loop.
  //
  // GET and HEAD only. A 301 on a POST is turned into a GET by most clients and the body is dropped,
  // so an api call that happened to carry a trailing slash would fail silently rather than loudly.
  const navMethod = request.method === 'GET' || request.method === 'HEAD';
  if (navMethod && url.pathname.length > 1 && url.pathname.endsWith('/')){
    const to = new URL(url.toString());
    to.pathname = url.pathname.replace(/\/+$/, '');
    if (to.pathname === '') to.pathname = '/';
    return Response.redirect(to.toString(), 301);
  }

  // 1) someone navigated to a raw build filename -> send them to the canonical clean url
  const legacy = legacyClean(url.pathname, url.searchParams);
  if (legacy){
    const to = new URL(legacy, url.origin);
    // ?asset= / ?pool= became a path segment, so carrying THEM would duplicate the identifier — but
    // dropping the whole query took every OTHER param with it. That silently broke the Wallet's
    // "Remove" button on an LP position, which links to ...?pool=<id>&act=withdraw so the pool page
    // opens on the Withdraw tab: the redirect promoted the pool into the path and threw act= away, so
    // the user always landed on Deposit. Drop only the key that was promoted.
    const promoted = legacy.indexOf('/trade/stellar/') === 0
      || legacy.indexOf('/pools/stellar/id/') === 0;
    if (promoted){
      const keep = new URLSearchParams(url.search);
      keep.delete('asset'); keep.delete('pool');
      const qs = keep.toString();
      to.search = qs ? ('?' + qs) : '';
    } else to.search = url.search;
    to.hash = url.hash;
    return Response.redirect(to.toString(), 301);
  }

  // 1b) /asset/stellar/<ASSET> -> /trade/stellar/<ASSET>, permanently.
  // The asset-overview page was removed; Trade-asset shows the same facts and can act on them.
  // These urls were published in the sitemap and may already be indexed, so this is a 301 rather
  // than a 404: search engines transfer the ranking to the Trade page instead of dropping it.
  // Bare /asset/stellar (no asset) goes to the Trade list.
  if (url.pathname === '/asset/stellar' || url.pathname.indexOf('/asset/stellar/') === 0){
    const rest = url.pathname.slice('/asset/stellar'.length);
    const to = new URL('/trade/stellar' + rest, url.origin);
    to.search = url.search;
    to.hash = url.hash;
    return Response.redirect(to.toString(), 301);
  }

  // 1c) THE THREE OPEN URL PATTERNS. /trade/stellar/:asset, /account/stellar/:address and the two
  // /pools/stellar forms accepted literally any string, returned 200, built a unique title out of the
  // junk and self-canonicalised to it -- an unbounded space of indexable pages that burns crawl budget
  // and dilutes the real asset pages.
  //
  // AFTER THE REDIRECTS ABOVE, NOT BEFORE THEM. Placed first, this 404ed every url the app itself
  // navigates to: the pool page is reached by assigning location.href="lumoscore-amm-pool.html?pool=..."
  // from a page already at /trade/stellar/..., so the browser asks for
  // /trade/stellar/lumoscore-amm-pool.html -- three segments under /trade/stellar, whose last one is a
  // filename and not an asset id. legacyClean exists precisely to redirect that, and it never got the
  // chance. Every Pools-pool page on production returned "Not found" until this moved down.
  //
  // FORMAT ONLY, deliberately. Checking that the asset actually EXISTS would need an upstream call on
  // every request, and that upstream is exactly the one already proven to fail intermittently -- a
  // wobble there would start 404ing real assets, which is far worse than serving a well-formed one
  // that happens to be empty. A Stellar issuer is 56 base32 characters; a crawler does not invent
  // those, so the space stops being unbounded.
  if (malformedId(url.pathname)){
    return new Response('Not found', {
      status: 404,
      headers: {
        'content-type': 'text/plain; charset=utf-8',
        'cache-control': 'public, max-age=300',
        'x-robots-tag': 'noindex, nofollow',
      },
    });
  }

  const hit = match(url.pathname);

  // not a page route -> let Pages serve it as usual
  if (!hit) return next();

  const isMobile = MOBILE.test(request.headers.get('user-agent') || '');
  const wantMobile = isMobile && HAS_MOBILE.has(hit.mobile);

  // Desktop needs no rewrite — Pages already serves the right file for this url. Rewriting anyway
  // broke "/", whose desktop file is index: fetching /index just 308s back to /.
  // Vary is still set on BOTH branches, or a cache would hand a desktop page to a phone.
  const res = wantMobile
    ? await context.env.ASSETS.fetch(
        new Request(new URL('/' + hit.mobile, request.url).toString(), request))
    : await next();

  let out = new Response(res.body, res);
  out.headers.set('Vary', 'User-Agent');

  const ct = out.headers.get('content-type') || '';
  if (ct.indexOf('text/html') < 0) return out;

  // canonical is the clean url WITHOUT query or hash, on whatever host served this request
  const canonical = PRIMARY_ORIGIN + (url.pathname === '/' ? '/' : url.pathname.replace(/\/+$/, ''));
  const want = seoFor(url.pathname);

  let seo = null;
  if (want && want.kind === 'asset') {
    const f = await assetFacts(want.id);
    seo = assetSeo(f, want.id);
    seo.facts = f;
    // Only build a card when a logo actually exists, so a missing one stays a missing image
    // rather than an empty rectangle of brand colour.
    const ai = await adminImage(context.env, want.id);
    if (ai || (f && f.image)) seo.image = cardFor(want.id);
  }
  else if (want && want.kind === 'blog') {
    const post = await blogPost(context.env, want.slug);
    if (post) seo = blogSeo(post, PRIMARY_ORIGIN);
  }
  else if (want && want.kind === 'pool') {
    // XLM has no logo of its own, so the pair's other side is the one worth showing.
    const other = want.a === 'native' ? want.b : want.a;
    const pf = (other && other !== 'native') ? await assetFacts(other) : null;
    const ai = (other && other !== 'native') ? await adminImage(context.env, other) : '';
    seo = poolSeo(want.a, want.b, (ai || (pf && pf.image)) ? cardFor(other) : '');
  }

  const head = [
    '<link rel="canonical" href="' + esc(canonical) + '">',
    '<meta property="og:url" content="' + esc(canonical) + '">',
    '<meta property="og:site_name" content="LumosCore">',
    '<meta property="og:type" content="website">',
  ];
  // Ask for the card type that matches the image we actually have.
  head.push('<meta name="twitter:card" content="'
    + ((seo && isCardImage(seo.image)) ? 'summary_large_image' : 'summary') + '">');
  if (seo){
    head.push('<meta property="og:title" content="' + esc(seo.title) + '">');
    head.push('<meta property="og:description" content="' + esc(seo.desc) + '">');
    head.push('<meta name="twitter:title" content="' + esc(seo.title) + '">');
    head.push('<meta name="twitter:description" content="' + esc(seo.desc) + '">');
    seo.image = absUrl(seo.image);
    // A crawler reads the page first and fetches og:image a moment later. Building the card now,
    // without holding up this response, means that second request usually finds it already cached
    // instead of paying the cold 2-3s that made a link need pasting two or three times.
    if (isCardImage(seo.image)) {
      try { context.waitUntil(fetch(seo.image, { headers: { accept: 'image/*' } })); } catch (e) {}
    }
    if (seo.image){
      head.push('<meta property="og:image" content="' + esc(seo.image) + '">');
      head.push('<meta property="og:image:alt" content="' + esc(seo.title) + '">');
      head.push('<meta name="twitter:image" content="' + esc(seo.image) + '">');
    }
    // a description already exists from the build; replace rather than duplicate
    head.push('<meta name="lx-seo-desc" content="' + esc(seo.desc) + '">');
  }

  // ---- structured data -------------------------------------------------------------------------
  // Organization and WebSite go on every page: they are what lets a search or answer engine attribute
  // a statement to a publisher rather than to an anonymous URL. The details are the registered ones.
  const ld = [{
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': PRIMARY_ORIGIN + '/#organization',
    name: 'LumosCore',
    legalName: 'LumosCore OÜ',
    url: PRIMARY_ORIGIN + '/',
    logo: PRIMARY_ORIGIN + '/assets/favicon.png',
    foundingLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressCountry: 'EE' } },
    identifier: '17336483',
    sameAs: [
      'https://x.com/LumosCore',
      'https://t.me/lumoscore',
      'https://www.linkedin.com/company/lumoscore/',
    ],
  }, {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': PRIMARY_ORIGIN + '/#website',
    url: PRIMARY_ORIGIN + '/',
    name: 'LumosCore',
    publisher: { '@id': PRIMARY_ORIGIN + '/#organization' },
    inLanguage: 'en',
  }];

  // Breadcrumbs only where there is a real hierarchy to describe.
  const crumbs = [];
  const segsC = url.pathname.split('/').filter(Boolean);
  if (segsC.length){
    crumbs.push({ '@type': 'ListItem', position: 1, name: 'Home', item: PRIMARY_ORIGIN + '/' });
    let acc = '';
    segsC.forEach(function(sg, i){
      acc += '/' + sg;
      crumbs.push({
        '@type': 'ListItem',
        position: i + 2,
        name: decodeURIComponent(sg).replace(/-/g, ' ').slice(0, 60),
        item: PRIMARY_ORIGIN + acc,
      });
    });
    ld.push({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: crumbs,
    });
  }

  // An article is a distinct entity with its own dates and author.
  if (seo && seo.post){
    const p = seo.post;
    const iso = (v) => { try { return new Date(+v || v).toISOString(); } catch (e) { return undefined; } };
    ld.push({
      '@context': 'https://schema.org',
      '@type': 'BlogPosting',
      headline: String(p.title || '').slice(0, 110),
      description: seo.desc,
      image: seo.image || undefined,
      datePublished: iso(p.publishedAt || p.publishAt || p.createdAt),
      dateModified: iso(p.updatedAt || p.publishedAt || p.publishAt),
      author: { '@type': 'Organization', name: 'LumosCore', '@id': PRIMARY_ORIGIN + '/#organization' },
      publisher: { '@id': PRIMARY_ORIGIN + '/#organization' },
      mainEntityOfPage: { '@type': 'WebPage', '@id': canonical },
      keywords: Array.isArray(p.tags) ? p.tags.join(', ') : undefined,
      articleSection: p.category || undefined,
      inLanguage: 'en',
    });
  }

  head.push('<script type="application/ld+json" id="lx-ld-core">'
    + JSON.stringify(ld).split('</').join('<\/') + '</scr' + 'ipt>');

  let rw = new HTMLRewriter().on('head', new HeadInjector(head.join('')));
  if (seo){
    rw = rw.on('title', new TitleSetter(seo.title))
           .on('meta[name="description"]', {
             element(el){ el.setAttribute('content', seo.desc); },
           });
  }
  // The asset identity block ships as the design's USDC sample. Fill it with what this page is
  // actually about, so a crawler that never runs the page's JavaScript reads the right asset.
  // GATED ON THE ROUTE, NOT ON THE FACTS. assetFacts() depends on stellar.expert, and when that
  // subrequest comes back empty the block used to be skipped entirely -- leaving the design's USDC
  // sample in place, so the page told a non-rendering crawler it was USD Coin. Measured 2026-08-31:
  // every asset page served that way to GPTBot and ClaudeBot while answering correctly to Googlebot
  // and to browsers, which is the worst possible audience to get it wrong for.
  //
  // The code and the issuer are in the URL and need no upstream, so the identity is always corrected
  // and only the enrichment is conditional. A missing price is a missing line; it is never another
  // asset's name.
  if (want && want.kind === 'asset'){
    const f = seo && seo.facts ? seo.facts : null;
    const code = (f && f.code) || want.id.split('-')[0];
    const bits = [];
    if (f && f.price) bits.push('Price ' + fmtUsd(f.price));
    if (f && f.trustlines) bits.push(f.trustlines.toLocaleString('en-US') + ' trustlines');
    // The issuer's own words when they published any; otherwise a factual sentence rather than a
    // borrowed one. Never another asset's copy.
    const desc = (f && f.desc)
      || (code + ' is a Stellar asset'
          + (f && f.domain ? ' issued by ' + f.domain : '')
          + '. ' + (bits.length ? bits.join(' · ') + '. ' : '')
          + 'Trade it non-custodially on LumosCore from your own wallet.');
    rw = rw.on('.asset-name', new TextSetter(code))
           .on('.asset-description', new TextSetter(desc));
    // Always rewritten, even to an empty string: an asset with no home domain was otherwise left
    // showing the design's placeholder, which claims the issuer is circle.com. Blank is honest.
    // Text mode because this anchor also holds the globe icon, which setInnerContent would delete.
    rw = rw.on('a.website', new TextSetter((f && f.domain) || '', 'text'));
  }

  // THE ARTICLE ITSELF, for a crawler that runs no JavaScript.
  //
  // The post page ships an empty shell -- <h1></h1> and <article class="lx-post-body"></article> --
  // and the browser fills both from /lxapi/blog. So what a crawler received was 329 words of nav and
  // footer and not one word of the article, on the exact pages the backlink plan points at. Links to
  // a page whose body is invisible pass their authority to a nav bar.
  //
  // The post is already in hand: the metadata above reads it at request time to build the title and
  // description, so this costs no extra work. The client sets the same innerHTML on load, so it
  // overwrites this with identical content -- no duplication, and nothing visibly changes.
  if (want && want.kind === 'blog' && seo && seo.post){
    const p = seo.post;
    if (p.title) rw = rw.on('.lx-post-head h1', new TextSetter(String(p.title)));
    if (p.body) rw = rw.on('.lx-post-body', new HtmlSetter(p.body));
  }

  out = rw.transform(out);
  out.headers.set('Vary', 'User-Agent');
  return out;
}
